I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script call
    call Introducao
  File "game/scripts/Introducao.rpy", line 434, in script call
    call Johnny_negativa_1_b
  File "game/scripts/Introducao.rpy", line 457, in script
    Johnny  "Que tipo de pergunta é essa?!… Eu venho aqui porque eu quero"
Exception: Sayer 'Johnny' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script call
    call Introducao
  File "game/scripts/Introducao.rpy", line 434, in script call
    call Johnny_negativa_1_b
  File "game/scripts/Introducao.rpy", line 457, in script
    Johnny  "Que tipo de pergunta é essa?!… Eu venho aqui porque eu quero"
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Johnny' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Heart Beat 1.0
Sat Nov 19 22:03:10 2022
