I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script call
    call Johnny_Dia5
  File "game/scripts/Dia5Johnny.rpy", line 175, in script
    Johnny "Brigado vó! A senhora é demais! Vou separar a sua vitrola lá."
Exception: Sayer 'Johnny' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script call
    call Johnny_Dia5
  File "game/scripts/Dia5Johnny.rpy", line 175, in script
    Johnny "Brigado vó! A senhora é demais! Vou separar a sua vitrola lá."
  File "C:\Users\User\Documents\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Documents\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Johnny' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Heart Beat 1.0
Tue Nov 22 10:59:50 2022
