I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script call
    call Dia2_Raul_Priscila
  File "game/scripts/Dia2RaulPriscila.rpy", line 394, in script
    if(funk == True) and (rock == True) and (pop == True):
  File "game/scripts/Dia2RaulPriscila.rpy", line 394, in <module>
    if(funk == True) and (rock == True) and (pop == True):
NameError: name 'funk' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script call
    call Dia2_Raul_Priscila
  File "game/scripts/Dia2RaulPriscila.rpy", line 394, in script
    if(funk == True) and (rock == True) and (pop == True):
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/Dia2RaulPriscila.rpy", line 394, in <module>
    if(funk == True) and (rock == True) and (pop == True):
NameError: name 'funk' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Heart Beat 1.0
Fri Nov 25 18:42:27 2022
